import sqlite3

conn = sqlite3.connect('PostLabQ2DB.db')
print("Database Opened")

conn.execute('''
CREATE TABLE "RENTER" (
	"RENTER_ID"	INTEGER,
	"FIRST_NAME"	NVARCHAR(50) NOT NULL,
	"MIDDLE_INITIAL"	NVARCHAR(50) NOT NULL,
	"LAST_NAME"	NVARCHAR(50) NOT NULL,
	"ADDRESS"	NVARCHAR(80) NOT NULL,
	"STATE"	NVARCHAR(30) NOT NULL,
	"CITY"	NVARCHAR(30) NOT NULL,
	"POSTAL_CODE"	NVARCHAR(10) NOT NULL,
	"PHONE_NUMBER"	NVARCHAR(20) NOT NULL,
	"EMAIL"	NVARCHAR(50) NOT NULL,
	PRIMARY KEY("RENTER_ID")
);

CREATE TABLE "PROPERTY" (
	"PROPERTY_ID"	INTEGER,
	"LOCATION_ID"	INTEGER NOT NULL,
	"UNIT_NUMBER"	INTEGER NOT NULL,
	"MAX_NUM_PERSON"	INTEGER NOT NULL,
	"BASE_WEEK_RATE"	INTEGER NOT NULL,
	FOREIGN KEY("LOCATION_ID") REFERENCES "LOCATION",
	PRIMARY KEY("PROPERTY_ID")
);

CREATE TABLE "LOCATION" (
	"LOCATION_ID"	INTEGER,
	"LOCATION_NAME"	NVARCHAR(80) NOT NULL,
	"ADDRESS"	NVARCHAR(80) NOT NULL,
	"STATE"	NVARCHAR(30) NOT NULL,
	"CITY"	NVARCHAR(30) NOT NULL,
	"POSTAL_CODE"	NVARCHAR(10) NOT NULL,
	PRIMARY KEY("LOCATION_ID")
);

CREATE TABLE "condoUnit" (
	"CONDO_ID"	INTEGER NOT NULL,
	"SQ_FEET"	INTEGER NOT NULL,
	"BEDROOMS"	INTEGER NOT NULL,
	"BATHROOMS"	INTEGER NOT NULL,
	"CONDO_FEE"	INTEGER NOT NULL,
	"LOCATION_ID"	INTEGER NOT NULL,
	FOREIGN KEY("LOCATION_ID") REFERENCES "LOCATION"
);

CREATE TABLE "rentAgreement" (
	"AGREEMENT_ID"	INTEGER NOT NULL,
	"RENTER_ID"	INTEGER NOT NULL,
	"START_DATE"	DATETIME NOT NULL,
	"END_DATE"	DATETIME NOT NULL,
	"RENT_AMOUNT"	INTEGER NOT NULL,
	"PROPERTY_ID"	INTEGER NOT NULL,
	FOREIGN KEY("RENTER_ID") REFERENCES "RENTER",
	FOREIGN KEY("PROPERTY_ID") REFERENCES "PROPERTY"
);
''')
print("Tables created successfully");
conn.close()